### ISSUE TITLE
🙌 golint!

### ISSUE THREAD

**Issue by b5** [ipfs/go-ipfs#4668]
Just want to say a **big** thank you to @hsanjuan & co for the linting work I'm seeing around the go repos. These comments help keeping up with changes much easier.

Side note, I know it's totally premature and may not be desired, but adding this to circleci where applicable has helped us a bunch:
```yaml
- run: 
  name: Run Lint Tests
  command: golint -set_exit_status ./...
```

that is all, feel free to close this at will.
