### ISSUE TITLE
ipfs add panics under Gitlab Runner

### ISSUE THREAD

**Issue by WyseNynja** [ipfs/go-ipfs#4998]
#### Version information:
```
$ ipfs version --all
go-ipfs version: 0.4.14-5db3846
Repo version: 6
System version: amd64/linux
Golang version: go1.9.4
```

(also fails under 0.4.13 and 0.4.15-rc1)

#### Type:
Bug

#### Description:
A few weeks ago I setup a Gitlab job that runs `ipfs add` and then updates my DNS server. This was working great 2 weeks ago, but when I went to update a site today, I got this error:

```
Running with gitlab-runner 10.6.0 (a3543a27)
  on leafblower 273e0857
Using Docker executor with image ipfs/go-ipfs:v0.4.14 ...
Pulling docker image ipfs/go-ipfs:v0.4.14 ...
Using docker image sha256:318eb01cab621e5fa4a1f40dfbdbe822c04e4c1a22b36dbb13400d1c34a454ce for ipfs/go-ipfs:v0.4.14 ...
Running on runner-273e0857-project-84-concurrent-0 via 29e774d0b471...
Fetching changes...
Removing ipfs_hash
HEAD is now at d8da9f2 do that in ipfs-dnslink
From https://gitlab.stytt.com/static/bryan.stitthappens.com
   d8da9f2..15d23b3  master     -> origin/master
Checking out 15d23b36 as master...
Skipping Git submodules setup
$ echo "IPFS_API is $IPFS_API"
IPFS_API is /ip4/10.11.12.130/tcp/5001
$ ipfs version --all
go-ipfs version: 0.4.14-5db3846
Repo version: 6
System version: amd64/linux
Golang version: go1.9.4
$ ipfs --api="$IPFS_API" add --pin=false ./site/index.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11ec2e4]
 
goroutine 22 [running]:
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http.parseResponse(0xc420126cf0, 0xc4204daaf0, 0xc420126cf0, 0x0, 0x0, 0xc420022de0)
    /go/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http/parse.go:215 +0x304
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http.(*client).Send(0xc4204fcf00, 0xc4204daaf0, 0xc4204dabd0, 0x1d55340, 0xc42044b200, 0x1)
    /go/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http/client.go:178 +0x515
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http.(*client).Execute(0xc4204fcf00, 0xc4204daaf0, 0x1d55340, 0xc42044b200, 0x1d466c0, 0xc4204fcec0, 0x0, 0x0)
    /go/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http/client.go:108 +0xde
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli.Run.func4(0x7fa3ce991030, 0xc4204fcf00, 0xc4204daaf0, 0x1d55380, 0xc4204dabd0, 0x1d466c0, 0xc4204fcec0, 0xc420059440)
    /go/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli/run.go:146 +0x70
created by gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli.Run
    /go/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli/run.go:145 +0x6ed
ERROR: Job failed: exit code 2
```

If I use the docker container to `ipfs add` on leafblower, everything works fine. This probably means it is an issue with GitLab and not IPFS itself, so I've opened a support ticket with them, too.

This is the IPFS part of my .gitlab-ci.yml:
```
# https://gitlab.stytt.com/groups/static/-/settings/ci_cd
# - IPFS_API=/ip4/10.11.12.130/tcp/5001

stages:
- upload

ipfs add:
  stage: upload
  image:
    name: ipfs/go-ipfs:master
    entrypoint: [""]
  script:
    - echo "IPFS_API is $IPFS_API"
    - ipfs version --all
    # debugging...
    - ipfs --api="$IPFS_API" add --pin=false ./site/index.html
    - ipfs --api="$IPFS_API" add --hidden --recursive ./site
    # end debugging...
    - ipfs --api="$IPFS_API" add --hidden --pin --quieter --recursive ./site >ipfs_hash
    - cat ipfs_hash
```

Any ideas how to get more useful logs out of ipfs? I can run `ipfs --api="$IPFS_API" add --hidden --pin --quieter --recursive ./site ` on my laptop just fine with and without docker. It's just under gitlab that it dies.

My previous successes were using gitlab-runner 10.6.0, so I rolled back to that version from 10.7, but that doesn't seem to have made any difference.
