### ISSUE TITLE
Support for ipfs add <url>

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#6065]
#### Version information:

```yaml
go-ipfs version: 0.4.19-
Repo version: 7
System version: arm64/android
Golang version: go1.11.5
```

#### Type: 

enhancement

#### Description:

I noticed that IPFS Cluster supported `ipfs-cluster-ctl add <url>`, but that feature isn't in IPFS. I think it's a pretty amazing command and I'd rather use that than `urlstore`.

Relevant : https://github.com/ipfs/ipfs-cluster/issues/701#issuecomment-470753292
