### ISSUE TITLE
Docker image permission denied for ipfs user

### ISSUE THREAD

**Issue by kyledewy** [ipfs/go-ipfs#6426]
#### Version information:
Docker image from official repository:
ipfs/go-ipfs:latest
Docker version 18.06.3
docker-compose version 1.24.0

#### Description:
I am trying to run the ipfs image from https://hub.docker.com/r/ipfs/go-ipfs/ in a docker-compose file. 
```
version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:master
    hostname: ipfs-node
    volumes:
    - "./export:/export"
    - "./data/ipfs:/data/ipfs"
    ports:
    - "5001:5001"
    - "4001:4001"
    - "8080:8080"
```

`docker-compose up` results in the following error: 
```
ipfs_1  | Changing user to ipfs
ipfs_1  | chown: /data/ipfs: Permission denied
ipfs_ipfs_1 exited with code 1

```
This compose file used to build and run without errors, however this permissions issue 
has come up in recent weeks for me.
