### ISSUE TITLE
Could not build arguments for function "reflect".makeFuncStub

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#6467]
#### Version information:

```yaml
OS: Windows 10 Pro Insider Preview x86_64
Resolution: 1920x1080
DE: Aero
WM: Explorer
CPU: Intel i5-3570K (4) @ 3.468GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 8135MiB
```

```yaml
go-ipfs version: 0.4.22-dev-
Repo version: 7
System version: amd64/windows
Golang version: go1.12.6
```

#### Description:

When running `ipfs daemon`, I get the following error : 

> Initializing daemon...
> go-ipfs version: 0.4.22-dev-
> Repo version: 7
> System version: amd64/windows
> Golang version: go1.12.6
> 23:18:09.434 ERROR   cmd/ipfs: error from node construction:  could not build arguments for function "reflect".makeFuncStub (C:/ProgramData/scoop/apps/go/current/src/reflect/asm_amd64.s:12): failed to build provider.System: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".SimpleProviderSys.func1 (C:/Users/natob/Go/src/github.com/ipfs/go-ipfs/core/node/provider.go:40): failed to build provider.Provider: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".SimpleProvider (C:/Users/natob/Go/src/github.com/ipfs/go-ipfs/core/node/provider.go:27): failed to build *queue.Queue: function "github.com/ipfs/go-ipfs/core/node".ProviderQueue (C:/Users/natob/Go/src/github.com/ipfs/go-ipfs/core/node/provider.go:22) returned a non-nil error: strconv.ParseUint: parsing "": invalid syntax daemon.go:337
> 
> Error: could not build arguments for function "reflect".makeFuncStub (C:/ProgramData/scoop/apps/go/current/src/reflect/asm_amd64.s:12): failed to build provider.System: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".SimpleProviderSys.func1 (C:/Users/natob/Go/src/github.com/ipfs/go-ipfs/core/node/provider.go:40): failed to build provider.Provider: could not build arguments for function "github.com/ipfs/go-ipfs/core/node".SimpleProvider (C:/Users/natob/Go/src/github.com/ipfs/go-ipfs/core/node/provider.go:27): failed to build *queue.Queue: function "github.com/ipfs/go-ipfs/core/node".ProviderQueue (C:/Users/natob/Go/src/github.com/ipfs/go-ipfs/core/node/provider.go:22) returned a non-nil error: strconv.ParseUint: parsing "": invalid syntax

I have no idea what caused it to do that. I was running the node from [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop), when suddenly, I noticed IPFS wasn't running and that it had errored. I tried to manually run `ipfs daemon`, but then I got those errors. I hope I won't have to delete my storage, I have some important stuff in there for once...
