### ISSUE TITLE
go-critic: invalid pseudo-version: does not match version-control timestamp

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#6603]
#### Version information:

```yaml
OS: Android 10 aarch64
Host: google Pixel 3
Kernel: 4.9.165-gfff483291c07-ab5725533
Uptime: secs
Packages: 103 (dpkg), 1 (pkg)
Shell: bash 5.0.9
CPU: Qualcomm SDM845 (8) @ 1.766GHz
Memory: 2091MiB / 3546MiB
```

#### Description:

Error when trying to build.
```
go: github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)
go version go1.13rc1 android/arm64
bin/check_go_version 1.12
go install  "-asmflags=all='-trimpath='" "-gcflags=all='-trimpath='" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=4a87fea33" ./cmd/ipfs
go: github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)
make: *** [cmd/ipfs/Rules.mk:37: cmd/ipfs-install] Error 1
```
