### ISSUE TITLE
Can't build : Interrupt/Exception caught (code = 0xc0000005, addr = 0x7263535C)

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#6787]
#### Version information:

```yaml
go-ipfs version: 0.5.0-dev
Repo version: 7
System version: amd64/windows
Golang version: go1.13.5
```

```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 3.0.7-338.x86_64
Uptime: 1 hour, 5 mins
Packages: 2 (scoop)
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Custom
CPU: Intel i5-3570K (4) @ 3.468GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 7070MiB / 8135MiB
```

```markdown
GNU Make 4.2.1
Built for Windows32
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

#### Description:

I get an error while building `go-ipfs` on Windows 10.

> What you were doing when you experienced the bug.

`make install`

> Any error messages you saw, *where* you saw them, and what you believe may have caused them

```bat
C:\Users\natob\Go\src\github.com\ipfs\go-ipfs>make install
"C:\ProgramData\scoop\apps\make\current\bin\make.exe": Interrupt/Exception caught (code = 0xc0000005, addr = 0x7263535C)
```

> When possible, steps to reliably produce the bug.

```bat
go get github.com/ipfs/go-ipfs
cd %UserProfile%\go\src\github.com\ipfs\go-ipfs
make install
```
