### ISSUE TITLE
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/go-ipfs#7597]
#### Version information:

```log
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
        C:/Users/natob/Go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x20e
```

```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 10.0.19041
Uptime: 20 hours, 48 mins
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Custom
Terminal: Windows Terminal
CPU: Intel i5-3570K (4) @ 3.470GHz
Memory: 10395MiB / 24519MiB
```

```
go version go1.15 windows/amd64
```

#### Description:

I tried to compile the master branch, but the output can't run.

```log
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
        C:/Users/natob/Go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x20e
```

**Comment by jefft0** [comment]
FWIW, I got the same error. I am on Ubuntu 16.04. I just upgraded to go1.15. I pulled the latest go-ipfs , did make clean and make install .

**Comment by ryys1122** [comment]
Ubuntu 18.04  and go1.15, the same error.

**Comment by johnnymatthews** [comment]
Can you see if downgrading to the previous go version gets around this issue? If you're on Ubuntu you can run:

```bash
sudo snap remove go
sudo snap install go --channel=1.14/stable --classic
```

**Comment by jefft0** [comment]
That works for me on Ubuntu 16.04. I removed the Go installation and installed go1.14.7 . Then I did `make clean` and `make install`. Now I can run `ipfs daemon` .

**Comment by aschmahmann** [comment]
@marten-seemann ^^

**Comment by NatoBoram** [comment]
Wait, I didn't even know it was *a thing* to support more than one Go version. Why even bother?

**Comment by aidanharris** [comment]
This will be fixed once https://github.com/libp2p/go-libp2p-quic-transport/pull/171 is merged.

**Comment by NatoBoram** [comment]
It works!

```yaml
go-ipfs version: 0.8.0-dev-c5825c29a
Repo version: 10
System version: arm64/linux
Golang version: go1.15
```
