### ISSUE TITLE
Docker error: Permission denied when attempting to access /ipfs and /ipns within container

### ISSUE THREAD

**Issue by pirate** [ipfs/go-ipfs#7922]
I have the following `docker-compose.yml` setup:
```yml
version: '2.4'

services:
    ipfs:
        image: ipfs/go-ipfs:latest
        command: daemon --migrate=true --mount
        #privileged: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        devices:
            - /dev/fuse:/dev/fuse:rwm
        ports:
            - 8080:8080   # public gateway
            - 4001:4001   # public swarm UDP
            - 5001:5001   # private API
        volumes:
            - ./data/ipfs:/data/ipfs
            - ./data/export:/export
            #- ./data/shares/ipfs:/ipfs
            #- ./data/shares/ipns:/ipns
```

When I start the container with `docker-compose up` it reports that `/ipfs` and `/ipns` have been successfully mounted, but I'm unable to `ls` or `cd` into them as root from inside the container.
```logs
$ docker-compose up
Creating network "zerviceipfs_default" with the default driver
Creating zerviceipfs_ipfs_1 ... done
Attaching to zerviceipfs_ipfs_1
ipfs_1  | Changing user to ipfs
ipfs_1  | ipfs version 0.8.0-rc2
ipfs_1  | Found IPFS fs-repo at /data/ipfs
ipfs_1  | Initializing daemon...
ipfs_1  | go-ipfs version: 0.8.0-rc2-4080333
ipfs_1  | Repo version: 11
ipfs_1  | System version: amd64/linux
ipfs_1  | Golang version: go1.14.4
ipfs_1  | 2021/02/17 19:50:48 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
ipfs_1  | Swarm listening on /ip4/127.0.0.1/tcp/4001
...
ipfs_1  | Swarm announcing /ip4/76.71.247.47/tcp/4001
ipfs_1  | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1  | WebUI: http://0.0.0.0:5001/webui
ipfs_1  | IPFS mounted at: /ipfs
ipfs_1  | IPNS mounted at: /ipns
ipfs_1  | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1  | Daemon is ready
```
```bash
$ docker-compose exec --user=root ipfs /bin/sh
 / # whoami
root
/ # ls
ls: ./ipns: Permission denied
ls: ./ipfs: Permission denied
bin     data    dev     etc     export  home    lib     lib64   proc    root    sbin    sys     tmp     usr     var
/ # cd /ipfs
/bin/sh: cd: can't cd to /ipns: Permission denied
```

I'm trying to eventually mount `/ipfs` and `/ipns` as volumes so that the host OS can write files into them, but I cant even get them working within the container as regular non-volume folders first. The eventually goal is to be able to put a folder into `~/myfiles` on the host, and have it automatically uploaded by `ipfs` within the docker container without having to mess around with the `ipfs` cli to `add` files manually. Not sure if this ticket means that isn't possible yet: https://github.com/ipfs/roadmap/issues/90

**Comment by pirate** [comment]
Setting these configs fixed the permission denied error, but there are still problems.

1. `/etc/fuse.conf` uncomment this line:
```
...
user_allow_other
```

2. `/data/ipfs/config` change `FuseAllowOther` to `true`:
```
  ...
  "Mounts": {
    "FuseAllowOther": true,
    ...
  },
  ...
```

3. Mount `/etc/fuse.conf` from the host into Docker via `docker-compose.yml` volume:
```yml
services:
    ipfs:
        ...
        volumes:
            - /etc/fuse.conf:/etc/fuse.conf:ro
```

Now I can `cd`, `ls`, etc. everything within the container, but the folders are still empty and I'm unable to mount them as volumes on the host:
```bash
$ docker-compose exec --user=root ipfs /bin/sh -c 'ls /ipn*/**'
/ipns/12D3KooWCSPrazUW7QNcpvWJh3jaWzErz52SrKC9X6uXqB4XVp4c:

/ipns/local:
```
Despite having a test file uploaded and pinned in my IPFS web dashboard, both these folders in `/ipns` (and `/ipfs`) are empty and do not contain my test file.

If I try to mount them as volumes on the host, not only are they empty but they don't even contain the empty `12D3K...` and `local` dirs that were visible from within the container.
