### ISSUE TITLE
Feature Request: Ability to Run as a kubernetes operator

### ISSUE THREAD

**Issue by Kampe** [ipfs/go-ipfs#8092]
Given adoption is a critical piece of IPFS infrastructure, I would say that having the ability for ipfs to be easily installed in a kubernetes cluster would be a massive win.

To facilitate this I think it's easiest to utilize a custom resource definition for an `IPFS Cluster` that would build out a cluster of size N and would configure the statefulset, configmaps and secret for the user to allow for applications to be utilized in a GitOps manner and would allow for some high level configurations at a resource level.

Allowing end users to install a single piece of yaml and be able to then create ipfs clusters simply by defining something like: 
(inspiration from https://github.com/rabbitmq/cluster-operator)

```
apiVersion: ipfs.io/v1beta1
kind: IPFSCluster
metadata:
    name: my-cluster
spec:
  replicas: 3
  ipfs:
    config: |
      gateway = enabled
```
